// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fumxndgyyehlbjjxcpgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1bXhuZGd5eWVobGJqanhjcGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTYxMzMsImV4cCI6MjA2NzYzMjEzM30.-v_gA4L9njnxOQE1S7xZ3MdQ_G32CwMfpPMpAZyoKHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});